<?php
array (
	'key' => 'field_56bdeebcdf17f',
	'label' => 'Gallery',
	'name' => 'gallery',
	'type' => 'gallery',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array (
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'min' => '',
	'max' => '',
	'preview_size' => 'thumbnail',
	'library' => 'all',
	'min_width' => '',
	'min_height' => '',
	'min_size' => '',
	'max_width' => '',
	'max_height' => '',
	'max_size' => '',
	'mime_types' => '',
)