<?php
array (
	'key' => 'field_56bdf1f5b863c',
	'label' => 'Repeater',
	'name' => 'repeater',
	'type' => 'repeater',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array (
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'collapsed' => 'field_56bdf1feb863d',
	'min' => '',
	'max' => '',
	'layout' => 'table',
	'button_label' => 'Add Row',
	'sub_fields' => array (
		array (
			'key' => 'field_56bdf1feb863d',
			'label' => 'Basic Text Box',
			'name' => 'basic_text_box',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
)