<?php
[
	'key'               => self::$slug . 'flexiblecontent',
	'label'             => __( 'Flexible Content', 'textdomain' ),
	'name'              => 'flexible_content',
	'type'              => 'flexible_content',
	'instructions'      => '',
	'required'          => 0,
	'conditional_logic' => 0,
	'wrapper'           => [
		'width' => '',
		'class' => '',
		'id'    => '',
	],
	'layouts'           => [
		self::$slug . 'samplelayout' => [
			'key'        => self::$slug . 'samplelayout',
			'name'       => 'sample_layout',
			'label'      => __( 'Sample layout', 'textdomain' ),
			'display'    => 'block',
			'sub_fields' => [
				[
					'key'               => self::$slug . 'flextext',
					'label'             => __( 'Flexible Text', 'textdomain' ),
					'name'              => 'flexible_text',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				],
			],
			'min'        => '',
			'max'        => '',
		],
	],
	'button_label'      => __( 'Add Row', 'textdomain' ),
	'min'               => '',
	'max'               => '',
],
