<?php
[
	'key'               => self::$slug . 'pagelink',
	'label'             => __( 'Page link', 'textdomain' ),
	'name'              => 'page_link',
	'type'              => 'page_link',
	'instructions'      => '',
	'required'          => 0,
	'conditional_logic' => 0,
	'wrapper'           => [
		'width' => '',
		'class' => '',
		'id'    => '',
	],
	'post_type'         => '',
	'taxonomy'          => '',
	'allow_null'        => 0,
	'allow_archives'    => 1,
	'multiple'          => 0,
],
