<?php
[
	'key'               => self::$slug . 'textarea',
	'label'             => __( 'Text Area', 'textdomain' ),
	'name'              => 'text_area',
	'type'              => 'textarea',
	'instructions'      => '',
	'required'          => 0,
	'conditional_logic' => 0,
	'wrapper'           => [
		'width' => '',
		'class' => '',
		'id'    => '',
	],
	'default_value'     => '',
	'placeholder'       => '',
	'maxlength'         => '',
	'rows'              => '',
	'new_lines'         => '',
],
