<?php
[
	'key'               => self::$slug . 'truefalse',
	'label'             => __( 'True/False', 'textdomain' ),
	'name'              => 'truefalse',
	'type'              => 'true_false',
	'instructions'      => '',
	'required'          => 0,
	'conditional_logic' => 0,
	'wrapper'           => [
		'width' => '',
		'class' => '',
		'id'    => '',
	],
	'message'           => '',
	'default_value'     => 0,
	'ui'                => 0,
	'ui_on_text'        => '',
	'ui_off_text'       => '',
],
