<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group( [
		'key' => 'group_59b92ab503589',
		'title' => 'Full Field Set',
		'fields' => [
			[
				'key' => 'FIELDKEY',
				'label' => 'Text',
				'name' => 'text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Textarea',
				'name' => 'textarea',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Range',
				'name' => 'range',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'min' => '',
				'max' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Url',
				'name' => 'url',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'placeholder' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Password',
				'name' => 'password',
				'type' => 'password',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'File',
				'name' => 'file',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'return_format' => 'array',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'WYSIWYG',
				'name' => 'wysiwyg',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'OEmbed',
				'name' => 'oembed',
				'type' => 'oembed',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'width' => '',
				'height' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Gallery',
				'name' => 'gallery',
				'type' => 'gallery',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'min' => '',
				'max' => '',
				'insert' => 'append',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Select',
				'name' => 'select',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'choices' => [
					'red' => 'Red',
					'blue' => 'Blue',
					'green' => 'Green',
				],
				'default_value' => [
					0 => 'blue',
				],
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Checkbox',
				'name' => 'checkbox',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'choices' => [
					'red' => 'Red',
					'green' => 'Green',
					'blue' => 'Blue',
				],
				'allow_custom' => 0,
				'save_custom' => 0,
				'default_value' => [
				],
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'value',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Radio Button',
				'name' => 'radio_button',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'choices' => [
					'red' => 'Red',
					'green' => 'Green',
					'blue' => 'Blue',
				],
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Button Group',
				'name' => 'button_group',
				'type' => 'button_group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'choices' => [
					'red' => 'Red',
					'green' => 'Green',
					'blue' => 'Blue',
				],
				'allow_null' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'True / False',
				'name' => 'true__false',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Link',
				'name' => 'link',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'return_format' => 'array',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Post Object',
				'name' => 'post_object',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'post_type' => [
				],
				'taxonomy' => [
				],
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'object',
				'ui' => 1,
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Page Link',
				'name' => 'page_link',
				'type' => 'page_link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'post_type' => [
				],
				'taxonomy' => [
				],
				'allow_null' => 0,
				'allow_archives' => 1,
				'multiple' => 0,
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Relationship',
				'name' => 'Relationship',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'post_type' => [
				],
				'taxonomy' => [
				],
				'filters' => [
					0 => 'search',
					1 => 'post_type',
					2 => 'taxonomy',
				],
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'object',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Taxonomy',
				'name' => 'taxonomy',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'taxonomy' => 'category',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'add_term' => 1,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'User',
				'name' => 'user',
				'type' => 'user',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'role' => '',
				'allow_null' => 0,
				'multiple' => 0,
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Google Map',
				'name' => 'google_map',
				'type' => 'google_map',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Date Picker',
				'name' => 'date_picker',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'display_format' => 'd/m/Y',
				'return_format' => 'd/m/Y',
				'first_day' => 1,
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Date Time Picker',
				'name' => 'date_time_picker',
				'type' => 'date_time_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'display_format' => 'd/m/Y g:i a',
				'return_format' => 'd/m/Y g:i a',
				'first_day' => 1,
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Time Picker',
				'name' => 'time_picker',
				'type' => 'time_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'display_format' => 'g:i a',
				'return_format' => 'g:i a',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Color Picker',
				'name' => 'color_picker',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'default_value' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Message',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'message' => 'Here is the message. It can have <strong>HTML</strong> in it.',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Tab',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'placement' => 'top',
				'endpoint' => 0,
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Group',
				'name' => 'group',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'layout' => 'block',
				'sub_fields' => [
					[
						'key' => 'FIELDKEY',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'FIELDKEY',
						'label' => 'Textarea',
						'name' => 'textarea',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					],
				],
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Repeater',
				'name' => 'repeater',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'collapsed' => 'field_5a0afe3344e4c',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => [
					[
						'key' => 'FIELDKEY',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					],
					[
						'key' => 'FIELDKEY',
						'label' => 'Textarea',
						'name' => 'textarea',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => [
							'width' => '',
							'class' => '',
							'id' => '',
						],
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					],
				],
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Flexible Content',
				'name' => 'flexible_content',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'layouts' => [
					'5a0afe53287d5' => [
						'key' => '5a0afe53287d5',
						'name' => 'first_layout',
						'label' => 'First Layout',
						'display' => 'block',
						'sub_fields' => [
							[
								'key' => 'FIELDKEY',
								'label' => 'Text',
								'name' => 'text',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => [
									'width' => '',
									'class' => '',
									'id' => '',
								],
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							],
						],
						'min' => '',
						'max' => '',
					],
					'5a0afe6e44e50' => [
						'key' => '5a0afe6e44e50',
						'name' => 'second_layout',
						'label' => 'Second Layout',
						'display' => 'block',
						'sub_fields' => [
							[
								'key' => 'FIELDKEY',
								'label' => 'Text',
								'name' => 'text',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => [
									'width' => '',
									'class' => '',
									'id' => '',
								],
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							],
						],
						'min' => '',
						'max' => '',
					],
				],
				'button_label' => 'Add Row',
				'min' => '',
				'max' => '',
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Clone',
				'name' => 'clone',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'clone' => [
					0 => 'field_5a0afc3d822f8',
					1 => 'field_5a0afc69822fa',
				],
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 0,
			],
			[
				'key' => 'FIELDKEY',
				'label' => 'Accordion',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
				],
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 0,
			],
		],
		'location' => [
			[
				[
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				],
			],
		],
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => 0,
		'description' => '',
	] );

endif;