<?php
array (
	'key' => 'FIELDKEY',
	'label' => 'Flexible Content',
	'name' => 'flexible_content',
	'type' => 'flexible_content',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array (
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'button_label' => 'Add Row',
	'min' => '',
	'max' => '',
	'layouts' => array (
		array (
			'key' => 'GROUPKEYA',
			'name' => 'content_group',
			'label' => 'Content Group',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'GROUPFIELDKEYA',
					'label' => 'Sample Text Field',
					'name' => 'sample_text_field',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
			'min' => '',
			'max' => '',
		),
		array (
			'key' => 'GROUPKEYB',
			'name' => 'another_content_group',
			'label' => 'Another Content Group',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'GROUPFIELDKEYB',
					'label' => 'Another Sample Text Field',
					'name' => 'another_sample_text_field',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
			'min' => '',
			'max' => '',
		),
	),
)