<?php
array (
	'key' => 'field_56bde9dcea67b',
	'label' => 'Image',
	'name' => 'image',
	'type' => 'image',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array (
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'return_format' => 'array',
	'preview_size' => 'thumbnail',
	'library' => 'all',
	'min_width' => '',
	'min_height' => '',
	'min_size' => '',
	'max_width' => '',
	'max_height' => '',
	'max_size' => '',
	'mime_types' => '',
)