<?php
[
	'key'               => 'FIELDKEY',
	'label'             => __( 'Number', 'textdomain' ),
	'name'              => 'number',
	'type'              => 'number',
	'instructions'      => '',
	'required'          => 0,
	'conditional_logic' => 0,
	'wrapper'           => [
		'width' => '',
		'class' => '',
		'id'    => '',
	],
	'default_value'     => '',
	'placeholder'       => '',
	'prepend'           => '',
	'append'            => '',
	'min'               => '',
	'max'               => '',
	'step'              => '',
],
